"""
Lean Source Snippets
====================
Assemble standalone Lean 4 source text from a Theorem + Proof so the Lean
client can type-check it. The encyclopedia stores statements and proofs
separately; this module joins them into a compilable line.
"""

from __future__ import annotations

from ..core.types import Theorem, Proof


def assemble(theorem: Theorem, proof: Proof) -> str:
    """Join a theorem statement with a proof into `... := <proof>`.

    Returns "" if either side is missing.
    """
    stmt = (theorem.lean_statement or "").strip()
    tac = (proof.lean_tactics or "").strip()
    if not stmt or not tac:
        return ""
    # If the statement already ends with `:=` (it shouldn't by convention),
    # don't add another one.
    joiner = " " if stmt.rstrip().endswith(":=") else " := "
    return f"{stmt}{joiner}{tac}"


def wrap_module(theorem: Theorem, proof: Proof) -> str:
    """A full standalone .lean source string for type-checking with `lean`."""
    line = assemble(theorem, proof)
    if not line:
        return ""
    return (
        "-- Auto-generated by the Leibniz engine for formal verification.\n"
        f"{line}\n"
    )
