"""
Stage: FORMALIZE (natural language → Lean)
==========================================
Autoformalization: translate an informal mathematical statement into a
candidate Lean 4 statement.

Two strategies:
  * Recognition (default, deterministic) — keyword-match the informal text
    against the encyclopedia; if a known theorem is recognised, return its
    stored Lean statement with high confidence. This is knowledge-base-
    assisted formalization: the encyclopedia IS the prior.
  * Generation (LLM backend) — for unknown statements, prompt the model to
    produce a fresh Lean statement, optionally seeded with the Mathlib
    concept index.

Output is a FormalizationResult: the candidate statement, a confidence
score, the source (recognised / generated), and the matched entry name.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional

from ..core.types import Theorem
from ..llm.backend import BaseBackend


@dataclass
class FormalizationResult:
    """The output of the formalize stage."""
    informal: str
    lean_statement: Optional[str] = None
    confidence: float = 0.0                 # 0.0 .. 1.0
    source: str = "none"                    # recognised | generated | none
    matched_entry: Optional[str] = None
    mathlib_refs: List[str] = field(default_factory=list)
    notes: str = ""


_STOPWORDS = {
    "a", "an", "the", "of", "is", "are", "was", "were", "be", "been", "being",
    "to", "in", "on", "for", "with", "and", "or", "if", "then", "that", "this",
    "it", "its", "as", "by", "at", "from", "every", "some", "any", "all", "each",
    "has", "have", "had", "do", "does", "did", "not", "no", "but", "than", "into",
    "over", "under", "about", "such", "there", "their", "we", "you", "they",
}


def _tokenize(s: str) -> List[str]:
    return [t for t in re.findall(r"[a-zA-Z][a-zA-Z0-9_-]*", (s or "").lower())
            if t not in _STOPWORDS and len(t) > 1]


def _score_overlap(query_tokens: List[str], entry) -> float:
    """Specificity-weighted overlap: rewards entries whose KEYWORDS appear in the
    query (precision), and whose keyword+name set covers the query (recall).
    Prose-only matches are weak to avoid common-word inflation."""
    q_set = set(query_tokens)
    if not q_set:
        return 0.0
    kw = {t.lower() for t in entry.get("keywords", [])}
    name = set(_tokenize(entry.get("name", "")))
    content = kw | name

    # precision: fraction of the entry's keywords present in the query (specificity)
    kw_precision = (len(kw & q_set) / len(kw)) if kw else 0.0
    # recall: fraction of query content tokens covered by keyword+name
    content_recall = (len(content & q_set) / len(q_set)) if q_set else 0.0
    return round(0.6 * kw_precision + 0.4 * content_recall, 3)


def formalize(informal: str, backend: Optional[BaseBackend] = None,
              threshold: float = 0.35) -> FormalizationResult:
    """Translate an informal statement into a candidate Lean statement.

    Strategy:
      1. Try to recognise a known encyclopedia theorem by keyword overlap.
         If the best score >= threshold, return its Lean statement.
      2. Otherwise, if an LLM backend is available, ask it to generate one.
      3. Otherwise return a low-confidence empty result.
    """
    from ..encyclopedia.lookup import default as default_enc
    enc = default_enc()

    q_tokens = _tokenize(informal)
    if not q_tokens:
        return FormalizationResult(informal=informal, notes="Empty input.")

    # --- 1. recognition over the encyclopedia ---
    best, best_score = None, 0.0
    for e in enc.all():
        sc = _score_overlap(q_tokens, e)
        if sc > best_score:
            best, best_score = e, sc

    if best is not None and best_score >= threshold and best.get("lean_statement"):
        refs = []
        if best.get("mathlib_ref"):
            refs.append(best["mathlib_ref"])
        return FormalizationResult(
            informal=informal,
            lean_statement=best["lean_statement"],
            confidence=min(1.0, best_score + 0.2),   # recognised entries are trusted
            source="recognised",
            matched_entry=best["name"],
            mathlib_refs=refs,
            notes=f"Recognised as '{best['name']}' (overlap {best_score:.2f}).",
        )

    # --- 2. generation via LLM (if a real backend is plugged in) ---
    if backend is not None and backend.name in ("hf", "remote"):
        stmt = _generate(informal, backend)
        if stmt:
            return FormalizationResult(
                informal=informal,
                lean_statement=stmt,
                confidence=0.4,
                source="generated",
                mathlib_refs=_extract_mathlib_refs(informal),
                notes="Generated by the LLM backend. Review the signature against Mathlib.",
            )

    # --- 3. fallback ---
    return FormalizationResult(
        informal=informal,
        confidence=best_score,
        source="none",
        matched_entry=(best["name"] if best else None),
        mathlib_refs=_extract_mathlib_refs(informal),
        notes=(f"Closest match '{best['name']}' ({best_score:.2f}) below threshold {threshold}. "
               f"Install/enable an LLM backend (LEIBNIZ_BACKEND=hf) for novel translation."
               if best else "No encyclopedia match; enable an LLM backend for translation."),
    )


def _generate(informal: str, backend: BaseBackend) -> Optional[str]:
    """Ask the LLM backend to translate informal → Lean (best effort)."""
    prompt = (
        "Translate this mathematical statement into a single Lean 4 theorem "
        "statement (no proof). Use Mathlib conventions. Reply with ONLY the "
        f"theorem header.\n\nStatement: {informal}\n\nLean 4:"
    )
    try:
        # HFBackend / RemoteBackend expose _generate; StubBackend does not.
        gen = backend._generate(prompt)  # type: ignore[attr-defined]
        if isinstance(gen, list):
            gen = gen[0] if gen else ""
        text = (gen or "").strip()
        # Extract the first `theorem ...` line.
        m = re.search(r"(theorem\s+\w+[\s\S]*?)\n\s*\n", text)
        if m:
            return m.group(1).strip()
        if text.startswith("theorem"):
            return text.split("\n")[0].strip()
    except Exception:
        return None
    return None


def _extract_mathlib_refs(informal: str) -> List[str]:
    """Pull out any Mathlib concept names present in the informal text."""
    from ..encyclopedia.lookup import default as default_enc
    enc = default_enc()
    try:
        import json, os
        path = os.path.join(os.path.dirname(enc.path), "mathlib_index.json")
        with open(path) as f:
            idx = json.load(f).get("concepts", {})
    except Exception:
        idx = {}
    q = informal.lower()
    refs = []
    for concept, meta in idx.items():
        if concept in q and meta.get("mathlib"):
            refs.append(meta["mathlib"])
    return refs
